// Embeds an exported forest JSON into the package as a gzipped, base64 Dart
// constant, so `spm screen` needs no asset lookup at run time and works from
// `dart pub global activate` and compiled executables alike.
//
//   dart run tool/embed_forest.dart path/to/forest_s_support_v1.json
//
// The JSON comes from `analysis_v2/export_forest_for_spm.py` in the thesis
// benchmark container.
import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

const _out = 'lib/src/features/screening/data/model/forest_data.g.dart';

void main(List<String> args) {
  if (args.length != 1) {
    stderr.writeln('usage: dart run tool/embed_forest.dart <forest.json>');
    exit(64);
  }
  final bytes = File(args.single).readAsBytesSync();
  final model = jsonDecode(utf8.decode(bytes)) as Map<String, dynamic>;
  final packed = base64.encode(GZipCodec(level: 9).encode(bytes));
  File(_out)
    ..parent.createSync(recursive: true)
    ..writeAsStringSync('''
// GENERATED by tool/embed_forest.dart. Do not edit.
// model: ${model['name']}
// source: ${model['source']}
// json sha256: ${sha256.convert(bytes)}
// ignore_for_file: lines_longer_than_80_chars

const forestName = '${model['name']}';
const forestJsonSha256 = '${sha256.convert(bytes)}';
const forestGzipBase64 = '$packed';
''');
  stdout.writeln('wrote $_out (${packed.length} base64 chars)');
}
